name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H 13.209.98.222 >> ~/.ssh/known_hosts

      - name: Deploy to EC2 and restart server
        run: |
          ssh ubuntu@13.209.98.222 '
            cd /home/ubuntu/api &&
            git pull &&
            npm install &&
            npm run dev &
          '
